### ISSUE TITLE
Update to 1.12.0

### ISSUE THREAD

**Issue by themaxdavitt** [jschneidereit/flatbuffer-choco#3]
Not making a PR because I don't know anything about chocolatey package definitions, but [version 1.12.0 was released a few months ago](https://github.com/google/flatbuffers/releases). Thanks for maintaining this!

**Comment by jschneidereit** [comment]
Hey there! Just submitted 1.12.0:

```
Attempting to push flatc.1.12.0.nupkg to https://push.chocolatey.org/
flatc 1.12.0 was pushed successfully to https://push.chocolatey.org/
```

**Comment by themaxdavitt** [comment]
That was fast, I really appreciate it!

**Comment by jschneidereit** [comment]
👍  no problem! it's available now: https://chocolatey.org/packages/flatc/1.12.0
